# Generated by Django 5.2.5 on 2025-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usuario_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
