# Generated by Django 5.2.5 on 2025-09-03 17:53

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_imagenpropiedad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propiedad",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="fecha_publicacion",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="imagen",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="propiedad",
            name="titulo",
        ),
        migrations.AddField(
            model_name="propiedad",
            name="area",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="bannos",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="fecha_disponibilidad",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="garaje",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="habitaciones",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="mascotas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="nombre",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="parqueaderos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="precio_m2",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="precio_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Piso", "Piso"),
                    ("Casa", "Casa"),
                    ("Chalet", "Chalet"),
                    ("Ático", "Ático"),
                    ("Dúplex", "Dúplex"),
                    ("Estudio", "Estudio"),
                    ("Loft", "Loft"),
                ],
                default="Piso",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="ubicacion",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="zonas_comunes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="descripcion",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="MediaPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="propiedades/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagen", "Imagen"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="core.propiedad",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ImagenPropiedad",
        ),
    ]
