# Generated by Django 5.2.4 on 2025-09-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_propiedad_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='bannos',
            new_name='banos',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('Piso', 'Piso'), ('Casa', 'Casa'), ('Chalet', 'Chalet'), ('Ático', 'Ático'), ('Dúplex', 'Dúplex'), ('Estudio', 'Estudio'), ('Loft', 'Loft'), ('Finca', 'Finca')], default='Piso', max_length=50),
        ),
    ]
