# Generated by Django 5.2.5 on 2025-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_bannos_propiedad_banos_alter_propiedad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapropiedad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='mediapropiedad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='banos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_disponibilidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='habitaciones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='parqueaderos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(choices=[('Piso', 'Piso'), ('Casa', 'Casa'), ('Chalet', 'Chalet'), ('Ático', 'Ático'), ('Dúplex', 'Dúplex'), ('Estudio', 'Estudio'), ('Loft', 'Loft'), ('Finca', 'Finca')], default='Piso', max_length=20),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['precio_total'], name='core_propie_precio__13e564_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['area'], name='core_propie_area_76caff_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['ubicacion'], name='core_propie_ubicaci_8f1353_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['tipo'], name='core_propie_tipo_97da3b_idx'),
        ),
    ]
