# Generated by Django 5.2.5 on 2025-09-24 21:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="", max_length=200)),
                ("descripcion", models.TextField(default="")),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "precio_m2",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("habitaciones", models.PositiveIntegerField(default=1)),
                ("banos", models.PositiveIntegerField(default=1)),
                ("parqueaderos", models.PositiveIntegerField(default=0)),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("ubicacion", models.CharField(default="", max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Piso", "Piso"),
                            ("Casa", "Casa"),
                            ("Chalet", "Chalet"),
                            ("Ático", "Ático"),
                            ("Dúplex", "Dúplex"),
                            ("Estudio", "Estudio"),
                            ("Loft", "Loft"),
                            ("Finca", "Finca"),
                        ],
                        default="Piso",
                        max_length=20,
                    ),
                ),
                ("zonas_comunes", models.TextField(blank=True, null=True)),
                ("fecha_disponibilidad", models.DateField(blank=True, null=True)),
                ("garaje", models.BooleanField(default=False)),
                ("mascotas", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propiedades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="propiedades/"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("imagen", "Imagen"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="properties.propiedad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="properties.propiedad",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["precio_total"], name="properties__precio__3fd254_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(fields=["area"], name="properties__area_0ff3af_idx"),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(
                fields=["ubicacion"], name="properties__ubicaci_a433e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propiedad",
            index=models.Index(fields=["tipo"], name="properties__tipo_6b78e4_idx"),
        ),
    ]
