# Generated by Django 5.2.5 on 2025-10-09 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Propiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Apartamento", "Apartamento"),
                            ("Casa", "Casa"),
                            ("Lote", "Lote"),
                            ("Oficina", "Oficina"),
                            ("Otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=100, null=True)),
                ("seller", models.CharField(blank=True, max_length=255, null=True)),
                ("listing_url", models.URLField(blank=True, null=True)),
                ("area_m2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "area_privada_m2",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("parking_spaces", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("estrato", models.IntegerField(blank=True, null=True)),
                ("antiguedad", models.CharField(blank=True, max_length=50, null=True)),
                ("cantidad_de_pisos", models.IntegerField(blank=True, null=True)),
                (
                    "codigo_fincaraiz",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amenities", models.JSONField(blank=True, null=True)),
                ("price_cop", models.BigIntegerField()),
                ("admin_fee_cop", models.BigIntegerField(blank=True, null=True)),
                ("pets_allowed", models.BooleanField(default=False)),
                ("furnished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propiedades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaPropiedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="propiedades/"),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[("imagen", "Imagen"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="properties.propiedad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("mensaje", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "propiedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_messages",
                        to="properties.propiedad",
                    ),
                ),
            ],
        ),
    ]
