# Generated by Django 5.2.5 on 2025-09-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="ascensor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="construccion_ano",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="estrato",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="piso",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
