# Generated by Django 5.2.7 on 2025-10-16 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propiedad_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-fecha_envio', '-id']},
        ),
        migrations.AlterModelOptions(
            name='mediapropiedad',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='propiedad',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='mediapropiedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediapropiedad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mediapropiedad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='propiedades/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='area_privada_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
